# Generated by Django 5.0.6 on 2024-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_product_id_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(default='', max_length=70)),
                ('user_adddres', models.CharField(max_length=50)),
                ('user_phone', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
